# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('date_reg', models.DateTimeField()),
            ],
        ),
    ]
