# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dentaire', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetDentaire',
            fields=[
                ('id_cabinet', models.AutoField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField(max_length=30)),
                ('fax', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id_consultation', models.AutoField(primary_key=True, serialize=False)),
                ('contenue', models.CharField(max_length=254)),
                ('antecedant', models.CharField(max_length=254)),
                ('traitement', models.CharField(max_length=254)),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichePatient',
            fields=[
                ('id_fiche', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=254)),
                ('prenom', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('age', models.IntegerField(max_length=4)),
                ('sexe', models.CharField(max_length=254)),
                ('tel', models.IntegerField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('CNAM', models.CharField(max_length=254)),
                ('profession', models.CharField(max_length=254)),
                ('motif_consultation', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id_ordonnance', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('medicament', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id_rdv', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('num_rdv', models.IntegerField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('nom', models.CharField(max_length=254)),
                ('prenom', models.CharField(max_length=254)),
                ('tel', models.IntegerField(max_length=30)),
                ('address', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='rdv',
            name='id_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_patient', to='dentaire.Utilisateur'),
        ),
        migrations.AddField(
            model_name='rdv',
            name='id_secretaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_sec', to='dentaire.Utilisateur'),
        ),
        migrations.AddField(
            model_name='fichepatient',
            name='id_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fich_patient', to='dentaire.Utilisateur'),
        ),
        migrations.AddField(
            model_name='fichepatient',
            name='id_secretaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fich_sec', to='dentaire.Utilisateur'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='id_facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons_fact', to='dentaire.Facture'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='id_medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons_medecine', to='dentaire.Utilisateur'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='id_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons_patient', to='dentaire.Utilisateur'),
        ),
    ]
