# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 17:03
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dentaire', '0003_auto_20170608_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetdentaire',
            name='fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='cabinetdentaire',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='fichepatient',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
