# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentaire', '0005_auto_20170608_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='contenue',
            field=models.TextField(max_length=254),
        ),
    ]
