# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentaire', '0006_auto_20170608_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date_consultation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
