# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 00:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dentaire', '0007_auto_20170609_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id_medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons_medecine', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fichepatient',
            name='id_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fich_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fichepatient',
            name='id_secretaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fich_sec', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='id_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rdv',
            name='id_secretaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_sec', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
