# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentaire', '0014_auto_20170611_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='observation',
            field=models.CharField(max_length=254),
        ),
    ]
